name: Publish Artifacts
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache Konan
        uses: actions/cache@v5
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Publish To GitHub Packages
        run: |
          ./gradlew publishAllPublicationsToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
